service: echoapi
frameworkVersion: ">=3.1.1 <4.0.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-north-1
  profile: heap

functions:
  echoapi:
    handler: lambda.handler
    memorySize: 128
    timeout: 5
    events:
      - httpApi: '*'

package:
  patterns:
    - '!**'
    - lambda.js
